version: "3.8"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    networks:
      - db-network
      - adminer-network
    depends_on:
      - database

  prometheus:
    image: prom/prometheus
    user: root
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/config:/etc/prometheus
      - ./docker/prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring-network
    depends_on:
      - prometheus

networks:
  db-network:
    driver: bridge
  adminer-network:
    driver: bridge
  monitoring-network:
    driver: bridge
