{
 "title": "Beholder",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(service_response_time_seconds_sum, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Http Status Change HIstory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "changes(service_status{service=\"$service\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Status by service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_response_status{service=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (service_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time by service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(service_response_time_seconds_sum{service=\"$service\"}[5m]) / rate(service_response_time_seconds_count{service=\"$service\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}